/*
 *    MCreator note:
 *
 *    If you lock base mod element files, you can edit this file and the proxy files
 *    and they won't get overwritten. If you change your mod package or modid, you
 *    need to apply these changes to this file MANUALLY.
 *
 *    Settings in @Mod annotation WON'T be changed in case of the base mod element
 *    files lock too, so you need to set them manually here in such case.
 *
 *    Keep the ElementsCavesNotCliffs object in this class and all calls to this object
 *    INTACT in order to preserve functionality of mod elements generated by MCreator.
 *
 *    If you do not lock base mod element files in Workspace settings, this file
 *    will be REGENERATED on each build.
 *
 */
package net.celestiald.cavesnotcliffs;

import net.minecraftforge.fml.relauncher.SideOnly;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLServerAboutToStartEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLLoadCompleteEvent;
import net.minecraftforge.fml.common.network.FMLNetworkEvent;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.client.event.ModelRegistryEvent;

import net.minecraft.world.biome.Biome;
import net.minecraft.potion.Potion;
import net.minecraft.item.Item;
import net.minecraft.block.Block;
import net.celestiald.cavesnotcliffs.command.CommandCaveBiome;
import net.celestiald.cavesnotcliffs.content.CncMaterialContent;
import net.celestiald.cavesnotcliffs.content.DungeonChestContent;
import net.celestiald.cavesnotcliffs.content.OreDictionaryCompat;
import net.celestiald.cavesnotcliffs.handler.LavaCauldronHandler;
import net.celestiald.cavesnotcliffs.migration.ImportedHeightMapRebuildHandler;
import net.celestiald.cavesnotcliffs.stonecutter.CncGuiHandler;
import net.celestiald.cavesnotcliffs.world.CavesNotCliffsWorldType;
import net.celestiald.cavesnotcliffs.world.CavesNotCliffsWorldTypes;
import net.celestiald.cavesnotcliffs.world.LegacySchemaOnePopulationHandler;
import net.celestiald.cavesnotcliffs.world.LegacySchemaTwoFluidHandler;
import net.celestiald.cavesnotcliffs.world.WorldHeightBootstrap;
import net.celestiald.cavesnotcliffs.world.VirtualBiomeResolverRegistry;
import net.celestiald.cavesnotcliffs.network.TerrainContractNetwork;
import net.celestiald.cavebiomes.api.BiomeLayerAPI;
import net.celestiald.cavebiomes.api.IWorldVerticalBiomeProvider;

import java.util.function.Supplier;

@Mod(modid = CavesNotCliffs.MODID, version = CavesNotCliffs.VERSION,
		dependencies = "required-after:forge@[14.23.5.2860,);required-after:cavebiomesapi@[1.1.0,)")
public class CavesNotCliffs {
	public static final String MODID = "cavesnotcliffs";
	public static final String VERSION = "2.0.0";
	public static final SimpleNetworkWrapper PACKET_HANDLER = NetworkRegistry.INSTANCE.newSimpleChannel("cavesnotcliffs:a");
	public static CavesNotCliffsWorldType WORLD_TYPE;
	@SidedProxy(clientSide = "net.celestiald.cavesnotcliffs.ClientProxyCavesNotCliffs", serverSide = "net.celestiald.cavesnotcliffs.ServerProxyCavesNotCliffs")
	public static IProxyCavesNotCliffs proxy;
	@Mod.Instance(MODID)
	public static CavesNotCliffs instance;
	public ElementsCavesNotCliffs elements = new ElementsCavesNotCliffs();
	private final WorldHeightBootstrap worldHeightBootstrap = new WorldHeightBootstrap();
	private final IWorldVerticalBiomeProvider verticalBiomeProvider =
			(world, x, y, z, base) -> VirtualBiomeResolverRegistry.resolve(
					world, x, y, z, base);
	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		DungeonChestContent.registerTileEntity();
		// Creating the hidden alias registers it before level.dat or server.properties is parsed.
		if (WORLD_TYPE == null) {
			WORLD_TYPE = new CavesNotCliffsWorldType();
		}
		MinecraftForge.EVENT_BUS.register(worldHeightBootstrap);
		BiomeLayerAPI.register(verticalBiomeProvider);
		TerrainContractNetwork.initialize();
		MinecraftForge.EVENT_BUS.register(LavaCauldronHandler.INSTANCE);
		MinecraftForge.EVENT_BUS.register(ImportedHeightMapRebuildHandler.INSTANCE);
		MinecraftForge.EVENT_BUS.register(LegacySchemaOnePopulationHandler.INSTANCE);
		MinecraftForge.EVENT_BUS.register(LegacySchemaTwoFluidHandler.INSTANCE);
		MinecraftForge.EVENT_BUS.register(this);
		GameRegistry.registerWorldGenerator(elements, 5);
		GameRegistry.registerFuelHandler(elements);
		NetworkRegistry.INSTANCE.registerGuiHandler(this, new CncGuiHandler());
		elements.preInit(event);
		MinecraftForge.EVENT_BUS.register(elements);
		elements.getElements().forEach(element -> element.preInit(event));
		proxy.preInit(event);
	}

	@Mod.EventHandler
	public void init(FMLInitializationEvent event) {
		elements.getElements().forEach(element -> element.init(event));
		CncMaterialContent.registerSmelting();
		OreDictionaryCompat.register();
		proxy.init(event);
	}

	@Mod.EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		proxy.postInit(event);
	}

	@Mod.EventHandler
	public void loadComplete(FMLLoadCompleteEvent event) {
		// This initial pass makes the fixed wrapper names available to dedicated-server properties.
		// Later lifecycle passes pick up world types registered by later load-complete handlers.
		CavesNotCliffsWorldTypes.registerWrappers();
	}

	@Mod.EventHandler
	public void serverAboutToStart(FMLServerAboutToStartEvent event) {
		// Forge fires this immediately before loadAllWorlds, so every persisted wrapper name must
		// be registered before WorldInfo parses level.dat. The core hook runs the one-time cubic
		// import after vanilla creates its save handler/session lock and before WorldInfo is read.
		CavesNotCliffsWorldTypes.registerWrappers();
	}

	@SubscribeEvent
	@SideOnly(Side.CLIENT)
	public void clientConnected(FMLNetworkEvent.ClientConnectedToServerEvent event) {
		// This event is posted synchronously when the FML handshake completes and before the
		// vanilla join packet is handled, whose WorldType field is decoded by name.
		CavesNotCliffsWorldTypes.registerWrappers();
	}

	@Mod.EventHandler
	public void serverLoad(FMLServerStartingEvent event) {
		event.registerServerCommand(new CommandCaveBiome());
		elements.getElements().forEach(element -> element.serverLoad(event));
		proxy.serverLoad(event);
	}

	@SubscribeEvent
	public void registerBlocks(RegistryEvent.Register<Block> event) {
		event.getRegistry().registerAll(elements.getBlocks().stream().map(Supplier::get).toArray(Block[]::new));
	}

	@SubscribeEvent
	public void registerItems(RegistryEvent.Register<Item> event) {
		event.getRegistry().registerAll(elements.getItems().stream().map(Supplier::get).toArray(Item[]::new));
	}

	@SubscribeEvent
	public void registerBiomes(RegistryEvent.Register<Biome> event) {
		event.getRegistry().registerAll(elements.getBiomes().stream().map(Supplier::get).toArray(Biome[]::new));
	}

	@SubscribeEvent
	public void registerEntities(RegistryEvent.Register<EntityEntry> event) {
		event.getRegistry().registerAll(elements.getEntities().stream().map(Supplier::get).toArray(EntityEntry[]::new));
	}

	@SubscribeEvent
	public void registerPotions(RegistryEvent.Register<Potion> event) {
		event.getRegistry().registerAll(elements.getPotions().stream().map(Supplier::get).toArray(Potion[]::new));
	}

	@SubscribeEvent
	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		elements.registerSounds(event);
	}

	@SubscribeEvent
	@SideOnly(Side.CLIENT)
	public void registerModels(ModelRegistryEvent event) {
		elements.getElements().forEach(element -> element.registerModels(event));
	}
	static {
		FluidRegistry.enableUniversalBucket();
	}
}
